### ISSUE TITLE
Correct Meeting Numbering Scheme and Inform The Team

### ISSUE THREAD

**Issue by SelmanB** [bounswe/2021SpringGroup11#113]
Group meeting 10.4 and the others are labelled wrong. The initial integer in the group name should have meant the week number as was done in [previous semester](https://github.com/bounswe/2021SpringGroup11/wiki/CMPE352---Meeting-Notes). This issue is going to be resolved once:

- [ ] The labels of last meetings is changed.
- [ ] References to these meeting names detected and updated.
- [x] This detail is broadcast to all members.
- [x] Label of the [previous semester](https://github.com/bounswe/2021SpringGroup11/wiki/CMPE352---Meeting-Notes) in the wiki index updated. (This one is additional)

**Comment by SelmanB** [comment]
The meeting headers are collaboratively fixed as can be seen [here](https://github.com/bounswe/2021SpringGroup11/wiki).
