### ISSUE TITLE
Evaluation of the status of deliverables and its impact on your project plan for Milestone 3 Group Report

### ISSUE THREAD

**Issue by emindeniz99** [bounswe/2021SpringGroup11#195]
Evaluate the deliverables and the impacts on the project plan.
Deliverables:
- [x] Evaluation of Requirements by @emindeniz99  
- [x] Evaluation of UML Software Designs by @emindeniz99  
- [x] Evaluation of Scenarios and Mockups by @emindeniz99  
- [x] Evaluation of Project plan by @emindeniz99  
- [x] Evaluation of Communication Plan by @myasins 
- [x] Evaluation of RAM
- [x] Evaluation of Milestone Review by @myasins 

Deadline: 11.20.2021 - 16.00

**Comment by emindeniz99** [comment]
Evaluations are written to the codeshare page(our collaborative markdown editor).
