### ISSUE TITLE
Milestone 1 RAM  Review and Update

### ISSUE THREAD

**Issue by Hazerank** [bounswe/2021SpringGroup11#196]
Please review the RAM file and update regarding parts. All the members should contribute for his/her part and approve the information about his/herself.
Deadline: 20.11.2021 / 19.00

- [x] Bekir Tatar
- [x] Emin Deniz
- [x] Eren Altunoğlu
- [x] Fikri Cem Yılmaz
- [x] Hazar Çakır
- [x] Kürşat Bakış
- [x] Meltem Arslan
- [x] Mehmet Yasin Şeremet
- [x] Selman Berk Özkurt

**Comment by SelmanB** [comment]
The tasks are completed. I reviewed @myasins's completion as well, so this issue can be closed.
