### ISSUE TITLE
Scheduling Meeting Platforms/Bots

### ISSUE THREAD

**Issue by emindeniz99** [bounswe/2021SpringGroup11#7]
# Options
- [ ] [SurverMonkey](https://www.surveymonkey.com/mp/online-schedule-poll/)
- [x] [Standup.ly slack bot ](https://standuply.com/pricing)
- [x] [polly.ai slack/teams bot ](https://www.polly.ai/)
- [x] Google Sheets 
- [x] polls_by_paul - slack bot

| Name | Comment |
| ----------- | ----------- |
| polly.ai | It has 25 respond limit per month |
| Standup.ly | We can not see free features |
| Google Sheets | No easy to create poll and make decision |
| polls_by_paul  | It is very good for our team |
